export function getCountryCode(country) {
  if (!country) return null;

  const countryMap = {
    // América do Sul
    'brasil': 'BR',
    'brazil': 'BR',
    'argentina': 'AR',
    'chile': 'CL',
    'colombia': 'CO',
    'peru': 'PE',
    'uruguai': 'UY',
    'uruguay': 'UY',
    'paraguai': 'PY',
    'paraguay': 'PY',
    'bolivia': 'BO',
    'equador': 'EC',
    'ecuador': 'EC',
    'venezuela': 'VE',
    'guiana': 'GY',
    'guyana': 'GY',
    'suriname': 'SR',
    'guiana francesa': 'GF',
    'french guiana': 'GF',

    // América do Norte
    'estados unidos': 'US',
    'united states': 'US',
    'canada': 'CA',
    'mexico': 'MX',

    // Europa
    'portugal': 'PT',
    'espanha': 'ES',
    'spain': 'ES',
    'franca': 'FR',
    'france': 'FR',
    'italia': 'IT',
    'italy': 'IT',
    'alemanha': 'DE',
    'germany': 'DE',
    'reino unido': 'GB',
    'united kingdom': 'GB',
    'inglaterra': 'GB',
    'england': 'GB',
    'holanda': 'NL',
    'netherlands': 'NL',
    'belgica': 'BE',
    'belgium': 'BE',
    'suica': 'CH',
    'switzerland': 'CH',
    'austria': 'AT',
    'suecia': 'SE',
    'sweden': 'SE',
    'noruega': 'NO',
    'norway': 'NO',
    'dinamarca': 'DK',
    'denmark': 'DK',
    'finlandia': 'FI',
    'finland': 'FI',
    'polonia': 'PL',
    'poland': 'PL',
    'grecia': 'GR',
    'greece': 'GR',
    'russia': 'RU',
    'russia': 'RU',

    // Ásia
    'china': 'CN',
    'japao': 'JP',
    'japan': 'JP',
    'india': 'IN',
    'coreia do sul': 'KR',
    'south korea': 'KR',
    'singapura': 'SG',
    'singapore': 'SG',
    'hong kong': 'HK',
    'taiwan': 'TW',
    'indonesia': 'ID',
    'malasia': 'MY',
    'malaysia': 'MY',
    'tailandia': 'TH',
    'thailand': 'TH',
    'vietna': 'VN',
    'vietnam': 'VN',
    'filipinas': 'PH',
    'philippines': 'PH',

    // Oceania
    'australia': 'AU',
    'nova zelandia': 'NZ',
    'new zealand': 'NZ',

    // África
    'africa do sul': 'ZA',
    'south africa': 'ZA',
    'egito': 'EG',
    'egypt': 'EG',
    'nigeria': 'NG',
    'quenia': 'KE',
    'kenya': 'KE',
    'marrocos': 'MA',
    'morocco': 'MA',
    'angola': 'AO',
    'mocambique': 'MZ',
    'mozambique': 'MZ',
  };

  const normalizedCountry = country.toLowerCase().trim();
  return countryMap[normalizedCountry] || null;
}
